//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Pacagroup.Comercial.Creditos.FormsConsumer.ProxyCliente {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ProxyCliente.IClienteService")]
    public interface IClienteService {
        
        [System.ServiceModel.OperationContractAttribute(ProtectionLevel=System.Net.Security.ProtectionLevel.EncryptAndSign, Action="http://tempuri.org/IClienteService/ObtenerCliente", ReplyAction="http://tempuri.org/IClienteService/ObtenerClienteResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(Pacagroup.Comercial.Creditos.Dominio.Error), Action="http://tempuri.org/IClienteService/ObtenerClienteErrorFault", ProtectionLevel=System.Net.Security.ProtectionLevel.EncryptAndSign, Name="Error", Namespace="http://schemas.datacontract.org/2004/07/Pacagroup.Comercial.Creditos.Dominio")]
        Pacagroup.Comercial.Creditos.Dominio.Cliente ObtenerCliente(string numeroDocumento);
        
        [System.ServiceModel.OperationContractAttribute(ProtectionLevel=System.Net.Security.ProtectionLevel.EncryptAndSign, Action="http://tempuri.org/IClienteService/ObtenerCliente", ReplyAction="http://tempuri.org/IClienteService/ObtenerClienteResponse")]
        System.Threading.Tasks.Task<Pacagroup.Comercial.Creditos.Dominio.Cliente> ObtenerClienteAsync(string numeroDocumento);
        
        [System.ServiceModel.OperationContractAttribute(ProtectionLevel=System.Net.Security.ProtectionLevel.EncryptAndSign, Action="http://tempuri.org/IClienteService/ListarCliente", ReplyAction="http://tempuri.org/IClienteService/ListarClienteResponse")]
        Pacagroup.Comercial.Creditos.Dominio.Cliente[] ListarCliente();
        
        [System.ServiceModel.OperationContractAttribute(ProtectionLevel=System.Net.Security.ProtectionLevel.EncryptAndSign, Action="http://tempuri.org/IClienteService/ListarCliente", ReplyAction="http://tempuri.org/IClienteService/ListarClienteResponse")]
        System.Threading.Tasks.Task<Pacagroup.Comercial.Creditos.Dominio.Cliente[]> ListarClienteAsync();
        
        [System.ServiceModel.OperationContractAttribute(ProtectionLevel=System.Net.Security.ProtectionLevel.EncryptAndSign, Action="http://tempuri.org/IClienteService/BuscarCliente", ReplyAction="http://tempuri.org/IClienteService/BuscarClienteResponse")]
        Pacagroup.Comercial.Creditos.Dominio.Cliente[] BuscarCliente(Pacagroup.Comercial.Creditos.Dominio.Cliente cliente);
        
        [System.ServiceModel.OperationContractAttribute(ProtectionLevel=System.Net.Security.ProtectionLevel.EncryptAndSign, Action="http://tempuri.org/IClienteService/BuscarCliente", ReplyAction="http://tempuri.org/IClienteService/BuscarClienteResponse")]
        System.Threading.Tasks.Task<Pacagroup.Comercial.Creditos.Dominio.Cliente[]> BuscarClienteAsync(Pacagroup.Comercial.Creditos.Dominio.Cliente cliente);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IClienteServiceChannel : Pacagroup.Comercial.Creditos.FormsConsumer.ProxyCliente.IClienteService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ClienteServiceClient : System.ServiceModel.ClientBase<Pacagroup.Comercial.Creditos.FormsConsumer.ProxyCliente.IClienteService>, Pacagroup.Comercial.Creditos.FormsConsumer.ProxyCliente.IClienteService {
        
        public ClienteServiceClient() {
        }
        
        public ClienteServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ClienteServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ClienteServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ClienteServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public Pacagroup.Comercial.Creditos.Dominio.Cliente ObtenerCliente(string numeroDocumento) {
            return base.Channel.ObtenerCliente(numeroDocumento);
        }
        
        public System.Threading.Tasks.Task<Pacagroup.Comercial.Creditos.Dominio.Cliente> ObtenerClienteAsync(string numeroDocumento) {
            return base.Channel.ObtenerClienteAsync(numeroDocumento);
        }
        
        public Pacagroup.Comercial.Creditos.Dominio.Cliente[] ListarCliente() {
            return base.Channel.ListarCliente();
        }
        
        public System.Threading.Tasks.Task<Pacagroup.Comercial.Creditos.Dominio.Cliente[]> ListarClienteAsync() {
            return base.Channel.ListarClienteAsync();
        }
        
        public Pacagroup.Comercial.Creditos.Dominio.Cliente[] BuscarCliente(Pacagroup.Comercial.Creditos.Dominio.Cliente cliente) {
            return base.Channel.BuscarCliente(cliente);
        }
        
        public System.Threading.Tasks.Task<Pacagroup.Comercial.Creditos.Dominio.Cliente[]> BuscarClienteAsync(Pacagroup.Comercial.Creditos.Dominio.Cliente cliente) {
            return base.Channel.BuscarClienteAsync(cliente);
        }
    }
}
